using System;
using CommunityToolkit.Mvvm.ComponentModel;

namespace Mp3TagFree.Models
{
    public partial class AudioFile : ObservableObject
    {
        [ObservableProperty]
        private string _filePath = string.Empty;

        [ObservableProperty]
        private string _fileName = string.Empty;

        [ObservableProperty]
        private long _fileSize;

        [ObservableProperty]
        private string _duration = string.Empty;

        [ObservableProperty]
        private string _title = string.Empty;

        [ObservableProperty]
        private string _artist = string.Empty;

        [ObservableProperty]
        private string _album = string.Empty;

        [ObservableProperty]
        private uint _year;

        [ObservableProperty]
        private string _genre = string.Empty;

        [ObservableProperty]
        private uint _track;

        [ObservableProperty]
        private string _lyrics = string.Empty;

        [ObservableProperty]
        private byte[]? _albumArt;

        [ObservableProperty]
        private bool _isDirty;

        public string FileSizeFormatted
        {
            get
            {
                if (FileSize >= 1024 * 1024)
                    return $"{FileSize / 1024.0 / 1024.0:F2} MB";
                if (FileSize >= 1024)
                    return $"{FileSize / 1024.0:F2} KB";
                return $"{FileSize} Bytes";
            }
        }

        // Property change hooks generated by CommunityToolkit.Mvvm to track edits
        partial void OnTitleChanged(string value) => MarkDirty();
        partial void OnArtistChanged(string value) => MarkDirty();
        partial void OnAlbumChanged(string value) => MarkDirty();
        partial void OnYearChanged(uint value) => MarkDirty();
        partial void OnGenreChanged(string value) => MarkDirty();
        partial void OnTrackChanged(uint value) => MarkDirty();
        partial void OnLyricsChanged(string value) => MarkDirty();
        partial void OnAlbumArtChanged(byte[]? value) => MarkDirty();

        private void MarkDirty()
        {
            // Only set dirty if we are not loading. The loading code will reset IsDirty to false.
            IsDirty = true;
        }

        public void ClearDirty()
        {
            IsDirty = false;
        }
    }
}
